//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string RIGHTHAND1 = "righthand1";
        
        public const string FRONT_HIT = "front_hit";
        
        public const string DAVLENIE_OT_USCARENIA = "davlenie_ot_uscarenia";
        
        public const string LEFT_POVOROT = "left_povorot";
        
        public const string RIGHT_POVOROT = "right_povorot";
        
        public const string STOLCNOVENIA = "stolcnovenia";
    }
}
